name: Environment Example Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      buildType:
        description: 'Build type (debug or release)'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      releaseNotes:
        description: 'Release notes for this build'
        required: true
        default: 'New build with improvements and bug fixes'
      distributionGroups:
        description: 'Firebase App Distribution groups (comma-separated)'
        required: true
        default: 'testers'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # This is the key part - dynamically select the environment
    environment: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Log which environment we're using (for debugging)
      - name: Log environment information
        run: |
          echo "Using environment: ${{ github.event.inputs.environment }}"

      - name: Build APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          BUILD_TYPE: ${{ github.event.inputs.buildType }}
        run: |
          echo "Building $BUILD_TYPE APK..."
          if [ "$BUILD_TYPE" == "debug" ]; then
            ./gradlew assembleDebug
          else
            ./gradlew assembleRelease
          fi

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.environment }}-${{ github.event.inputs.buildType }}-apk
          path: app/build/outputs/apk/${{ github.event.inputs.buildType }}/*.apk

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Distribute to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          # Use environment-specific app IDs
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          RELEASE_NOTES: ${{ github.event.inputs.releaseNotes }}
          DISTRIBUTION_GROUPS: ${{ github.event.inputs.distributionGroups }}
          BUILD_TYPE: ${{ github.event.inputs.buildType }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          echo "Distributing $ENVIRONMENT $BUILD_TYPE APK to Firebase App Distribution..."

          # Find the APK path based on build type
          if [ "$BUILD_TYPE" == "debug" ]; then
            APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          else
            APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          fi

          echo "Using Firebase App ID: $FIREBASE_APP_ID"
          echo "APK Path: $APK_PATH"

          firebase appdistribution:distribute "$APK_PATH" \
            --app "$FIREBASE_APP_ID" \
            --release-notes "$RELEASE_NOTES" \
            --groups "$DISTRIBUTION_GROUPS" \
            --token "$FIREBASE_TOKEN"
